### ISSUE TITLE
Errors will be reported if xlsx extensions are used

### ISSUE THREAD

**Issue by hefeng1208** [m0rtadelo/to-excel#1]
![image](https://user-images.githubusercontent.com/24466340/64153452-7fa24000-ce61-11e9-9438-8e67e8019624.png)

**Comment by m0rtadelo** [comment]
The generation of XLSX files is not supported.
Generated files **must** use XML or XLS extension to be compatible with Microsoft Excel, LibreOffice Calc, etc. In fact XML extension is the proper one because is a XML file.
You can use Excel to create a XLSX file from generated XLS/XML using the "Save as" option.
